name: db-gpt

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "aa123456"
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - dbgpt-myql-db:/var/lib/mysql
      - ./DB-GPT/docker/examples/my.cnf:/etc/my.cnf
      - ./DB-GPT/docker/examples/sqls:/docker-entrypoint-initdb.d
      - ./DB-GPT/assets/schema/dbgpt.sql:/docker-entrypoint-initdb.d/dbgpt.sql
    restart: unless-stopped
    networks:
      - dbgptnet
  webserver:
    image: eosphorosai/dbgpt:latest
    command: python3 dbgpt/app/dbgpt_server.py
    environment:
      - LOCAL_DB_HOST=db
      - LOCAL_DB_PASSWORD=aa123456
      - ALLOWLISTED_PLUGINS=db_dashboard
      - LLM_MODEL=glm-4-9b-chat
    depends_on:
      - db
    volumes:
      - ./data:/data
      # Please modify it to your own model directory
      - ./data/models:/app/models
      - dbgpt-data:/app/pilot/data
      - dbgpt-message:/app/pilot/message
    env_file:
      - ./DB-GPT/.env.template
    ports:
      - 5670:5670/tcp
    # webserver may be failed, it must wait all sqls in /docker-entrypoint-initdb.d execute finish.
    restart: unless-stopped
    networks:
      - dbgptnet
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
volumes:
  dbgpt-myql-db:
  dbgpt-data:
  dbgpt-message:
networks:
  dbgptnet:
    driver: bridge
    name: dbgptnet
